### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by sethmlarson** [kislyuk/pyhttpsec#1]
Hello @kislyuk! Would you be opposed to letting me also have publish rights to the name `hstspreload` on PyPI? The last publish to the name was 2 years ago and I'd like to breathe new life into the project. :)

- I'll keep your name as author and an admin on the project
- Keep the same API
- The project will be structured to auto-publish new versions whenever the HSTS preload list changes on the upstream project.
- Will license the code as BSD-3 to match the license of the HSTS preload list.

Thoughts?

**Comment by kislyuk** [comment]
Hi @sethmlarson, thanks for reaching out! I will gladly hand this over to you as long as you add yourself as an author in any publication materials, and house it under https://github.com/python-http or encode or wherever httpx will be housed. I agree with all your other points.

**Comment by kislyuk** [comment]
Please confirm your PyPI username.

**Comment by sethmlarson** [comment]
Definitely will do! SethMichaelLarson is my handle on PyPI. :)

**Comment by kislyuk** [comment]
Added SethMichaelLarson as owner on https://pypi.org/project/hstspreload/.

**Comment by kislyuk** [comment]
I will archive this repo and add a link to the new location once you decide where it lives.

**Comment by sethmlarson** [comment]
https://github.com/sethmlarson/hstspreload :)
